version: "2.0"
services:
  neko:
    image: belleepoke/visionhub:latest
    restart: always
    shm_size: "1gb"
    volumes:
      - "./certs:/certs"
    ports:
      - "80:8080"
      - "59000-59100:59000-59100/udp"
    environment:
      DISPLAY: :99.0
      NEKO_PASSWORD: algebra
      NEKO_PASSWORD_ADMIN: algebra2
      NEKO_BIND: :8080
      NEKO_EPR: 59000-59100
      NEKO_CERT: /certs/html.casa.crt
      NEKO_KEY: /certs/html.casa.key